artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/rjdp07/churn_data_repo/raw/master/churn_dataset.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/Telecom Churn Rate Dataset.xlsx
  STATUS_FILE: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/Telecom Churn Rate Dataset.xlsx

model_trainer:
  root_dir: artifacts/model_trainer
  Xtrain_data_path: artifacts/data_transformation/X_train.csv
  Xtest_data_path: artifacts/data_transformation/X_test.csv
  ytrain_data_path: artifacts/data_transformation/y_train.csv
  ytest_data_path: artifacts/data_transformation/y_test.csv
  model_name: model.joblib